zshrc adjustments, plus new core.sh funcs: fresh,install_global,fix_locale

diff --git a/dotfiles/zshrc b/dotfiles/zshrc
--- a/dotfiles/zshrc
+++ b/dotfiles/zshrc
@@ -1,7 +1,14 @@
 # If you come from bash you might have to change your $PATH.
 # export PATH=$HOME/bin:/usr/local/bin:$PATH
 # Path to your oh-my-zsh installation.
-export ZSH="$HOME/.oh-my-zsh"
+if [[ -d "$HOME/.oh-my-zsh" ]]; then
+  export ZSH="$HOME/.oh-my-zsh"
+elif [[ -d "/etc/oh-my-zsh" ]]; then
+  export ZSH="/etc/oh-my-zsh"
+else
+  echo "CRITICAL ERROR: could not find oh-my-zsh in $HOME/.oh-my-zsh or /etc/oh-my-zsh"
+fi
+
 
 # Set name of the theme to load. Optionally, if you set this to "random"
 # it'll load a random theme each time that oh-my-zsh is loaded.
@@ -32,7 +39,7 @@ ZSH_THEME="fino"
 # ENABLE_CORRECTION="true"
 
 # Uncomment the following line to display red dots whilst waiting for completion.
-# COMPLETION_WAITING_DOTS="true"
+COMPLETION_WAITING_DOTS="true"
 
 # Uncomment the following line if you want to disable marking untracked files
 # under VCS as dirty. This makes repository status check for large repositories
@@ -60,16 +67,27 @@ source $ZSH/oh-my-zsh.sh
 # Global simple line separator used by the various helpers
 LINE="============================================"
 
-# load script helpers
-source ~/.zsh_files/colors.zsh      # Terminal colours such as $RED, $YELLOW etc.
-source ~/.zsh_files/gnusafe.zsh     # GNU Utility sanity checker
-source ~/.zsh_files/ssh.zsh         # Helpers such as await-ssh, ssh-reset
-source ~/.zsh_files/rsync.zsh       # brsync - better rsync
-source ~/.zsh_files/steem.zsh       # Steem RPC related e.g. rpc_rq, rpc_get_time
-if [[ "$(uname -s)" == "Darwin" ]]; then
-    source ~/.zsh_files/osx.zsh     # OSX specific functions
+# load zsh_files from homedir. if that's not found, try etc
+if [[ -d "$HOME/.zsh_files" ]]; then
+  ZSHFILES_DIR="$HOME/.zsh_files"
+elif [[ -d "/etc/zsh_files" ]]; then
+  ZSHFILES_DIR="/etc/zsh_files"
 fi
-source ~/.zsh_files/zshreload.zsh   # ZSH Hook to recommend reloading after editing zshrc
+
+if ! [ -z ${ZSHFILES_DIR+x} ]; then 
+  # load script helpers
+  source "$ZSHFILES_DIR/colors.zsh"      # Terminal colours such as $RED, $YELLOW etc.
+  source "$ZSHFILES_DIR/gnusafe.zsh"     # GNU Utility sanity checker
+  source "$ZSHFILES_DIR/ssh.zsh"         # Helpers such as await-ssh, ssh-reset
+  source "$ZSHFILES_DIR/rsync.zsh"       # brsync - better rsync
+  source "$ZSHFILES_DIR/steem.zsh"       # Steem RPC related e.g. rpc_rq, rpc_get_time
+  if [[ "$(uname -s)" == "Darwin" ]]; then
+      source "$ZSHFILES_DIR/osx.zsh"     # OSX specific functions
+  fi
+  source "$ZSHFILES_DIR/zshreload.zsh"   # ZSH Hook to recommend reloading after editing zshrc
+else
+  echo "WARNING: failed to find ~/.zsh_files and /etc/zsh_files - some things may break..."
+fi
 
 # enable "help" for zsh built-ins
 # e.g. $ help read
@@ -107,6 +125,13 @@ alias activate="source venv/bin/activate"
 alias mkvenv="python3 -m venv venv; echo 'Made virtual env @ ./venv'"
 
 alias l='ls -lah'
+export LS_OPTIONS='--color=auto'
+if [ -x "$(command -v dircolors)" ]; then
+  eval "`dircolors`"
+  alias ls='ls $LS_OPTIONS'
+  alias ll='ls $LS_OPTIONS -l'
+  alias l='ls $LS_OPTIONS -lah'
+fi
 
 # Node Version Manager
 export NVM_DIR="$HOME/.nvm"
@@ -114,3 +139,17 @@ export NVM_DIR="$HOME/.nvm"
 [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
 
 export EDITOR='vim'
+
+# for Linux servers, if running as a normal user, alias important commands to use sudo
+if [[ "$(uname -s)" == "Linux" && [[ $UID != 0 && $EUID != 0 ]] ]]; then
+  alias su='sudo su -'
+  alias apt='sudo apt'
+  alias apt-get='sudo apt-get'
+  alias systemctl='sudo systemctl'
+  alias sysctl='sudo sysctl'
+  alias service='sudo service'
+  alias journalctl='sudo journalctl'
+  alias ip='sudo ip'
+  alias ifconfig='sudo ifconfig'
+  alias route='sudo route'
+fi
